MODULE constants
    IMPLICIT NONE
    PUBLIC
    CHARACTER(LEN=9), PARAMETER :: nl_name = "input.nl"
    CHARACTER(LEN=1), PARAMETER :: u_name = "u"
    CHARACTER(LEN=1), PARAMETER :: x_name = "X"
    DOUBLE PRECISION, PARAMETER :: G = 6.6743e-10
END MODULE
